# Предобработка данных
# Исследование надёжности заёмщиков

## 1. Постановка задачи
Заказчик — кредитный отдел банка. Нужно разобраться, влияет ли семейное положение и количество детей клиента на факт погашения кредита в срок. Входные данные от банка — статистика о платёжеспособности клиентов.

Результаты исследования будут учтены при построении модели **кредитного скоринга** — специальной системы, которая оценивает способность потенциального заёмщика вернуть кредит банку.


### Шаги выполнения проекта
#### Предобработка данных
1. В двух столбцах есть пропущенные значения. Один из них — days_employed. Пропуски в этом столбце вы обработаете на следующем этапе. Найдите другой столбец и заполните пропущенные значения в нём медианным значением:
    - опишите, какие пропущенные значения вы обнаружили;
    - проверьте, какую долю составляют пропущенные значения в каждом из столбцов с пропусками;
    - приведите возможные причины появления пропусков в данных;
    - объясните, почему заполнить пропуски медианным значением — лучшее решение для количественных переменных.
2. В данных могут встречаться артефакты (аномалии) — значения, которые не отражают действительность и появились по какой-то ошибке. Например, отрицательное количество дней трудового стажа в столбце days_employed. Для реальных данных это нормально. Обработайте значения в столбцах с аномалиями и опишите возможные причины появления таких данных. После обработки аномалий заполните пропуски в days_employed медианными значениями по этому столбцу.
3. Замените вещественный тип данных в столбце total_income на целочисленный, например, с помощью метода astype().
4. Если в данных присутствуют строки-дубликаты, удалите их. Также обработайте неявные дубликаты. Например, в столбце education есть одни и те же значения, но записанные по-разному: с использованием заглавных и строчных букв. Приведите такие значения к одному регистру.
После удаления дубликатов сделайте следующее:
    - поясните, как выбирали метод для поиска и удаления дубликатов в данных;
    - приведите возможные причины появления дубликатов.

5. Создайте два новых датафрейма, в которых:
    - каждому уникальному значению из education соответствует уникальное значение education_id — в первом;
    - каждому уникальному значению из family_status соответствует уникальное значение family_status_id — во втором.

    Удалите из исходного датафрейма столбцы education и family_status, оставив только их идентификаторы: education_id и family_status_id. Новые датафреймы — это те самые «словари» (не путайте с одноимённой структурой данных в Python), к которым вы сможете обращаться по идентификатору.

6. На основании диапазонов, указанных ниже, создайте столбец total_income_category с категориями:
    - 0–30000 — 'E';
    - 30001–50000 — 'D';
    - 50001–200000 — 'C';
    - 200001–1000000 — 'B';
    - 1000001 и выше — 'A'.

    Например, кредитополучателю с доходом 25000 нужно назначить категорию 'E', а клиенту, получающему 235000, — 'B'.

7. Создайте функцию, которая на основании данных из столбца purpose сформирует новый столбец purpose_category, в который войдут следующие категории:
    - 'операции с автомобилем',
    - 'операции с недвижимостью',
    - 'проведение свадьбы',
    - 'получение образования'.

    Например, если в столбце purpose находится подстрока 'на покупку автомобиля', то в столбце purpose_category должна появиться строка 'операции с автомобилем'.
    Вы можете использовать собственную функцию и метод apply(). Изучите данные в столбце purpose и определите, какие подстроки помогут вам правильно определить категорию.

#### Ответьте на вопросы
- Есть ли зависимость между количеством детей и возвратом кредита в срок?
- Есть ли зависимость между семейным положением и возвратом кредита в срок?
- Есть ли зависимость между уровнем дохода и возвратом кредита в срок?
- Как разные цели кредита влияют на его возврат в срок?



### Данные

Данные хранятся в файле `data/project_2.csv`.

**Описание данных:**
 - `children` — количество детей в семье
 - `days_employed` — общий трудовой стаж в днях
 - `dob_years` — возраст клиента в годах
 - `education` — уровень образования клиента
 - `education_id` — идентификатор уровня образования
 - `family_status` — семейное положение
 - `family_status_id` — идентификатор семейного положения
 - `gender` — пол клиента
 - `income_type` — тип занятости
 - `debt` — имел ли задолженность по возврату кредитов
 - `total_income` — ежемесячный доход
 - `purpose` — цель получения кредита

## 2. Получение данных

In [56]:
import polars as pl
pl.Config.set_fmt_str_lengths(100)
pl.Config.set_tbl_rows(20);

from common_functions.data_research_functions import pl_info

In [57]:
df = pl.read_csv('data/project_2.csv')
df.head(10)

shape: (10, 12)
┌──────────┬─────────────┬───────────┬───────────┬───┬────────────┬──────┬────────────┬────────────┐
│ children ┆ days_employ ┆ dob_years ┆ education ┆ … ┆ income_typ ┆ debt ┆ total_inco ┆ purpose    │
│ ---      ┆ ed          ┆ ---       ┆ ---       ┆   ┆ e          ┆ ---  ┆ me         ┆ ---        │
│ i64      ┆ ---         ┆ i64       ┆ str       ┆   ┆ ---        ┆ i64  ┆ ---        ┆ str        │
│          ┆ f64         ┆           ┆           ┆   ┆ str        ┆      ┆ f64        ┆            │
╞══════════╪═════════════╪═══════════╪═══════════╪═══╪════════════╪══════╪════════════╪════════════╡
│ 1        ┆ -8437.67302 ┆ 42        ┆ высшее    ┆ … ┆ сотрудник  ┆ 0    ┆ 253875.639 ┆ покупка    │
│          ┆ 8           ┆           ┆           ┆   ┆            ┆      ┆ 453        ┆ жилья      │
│ 1        ┆ -4024.80375 ┆ 36        ┆ среднее   ┆ … ┆ сотрудник  ┆ 0    ┆ 112080.014 ┆ приобретен │
│          ┆ 4           ┆           ┆           ┆   ┆            ┆      ┆ 102        ┆ ие         │
│          ┆             ┆           ┆           ┆   ┆            ┆      ┆            ┆ автомобиля │
│ 0        ┆ -5623.42261 ┆ 33        ┆ Среднее   ┆ … ┆ сотрудник  ┆ 0    ┆ 145885.952 ┆ покупка    │
│          ┆             ┆           ┆           ┆   ┆            ┆      ┆ 297        ┆ жилья      │
│ 3        ┆ -4124.74720 ┆ 32        ┆ среднее   ┆ … ┆ сотрудник  ┆ 0    ┆ 267628.550 ┆ дополнител │
│          ┆ 7           ┆           ┆           ┆   ┆            ┆      ┆ 329        ┆ ьное образ │
│          ┆             ┆           ┆           ┆   ┆            ┆      ┆            ┆ ование     │
│ 0        ┆ 340266.0720 ┆ 53        ┆ среднее   ┆ … ┆ пенсионер  ┆ 0    ┆ 158616.077 ┆ сыграть    │
│          ┆ 47          ┆           ┆           ┆   ┆            ┆      ┆ 87         ┆ свадьбу    │
│ 0        ┆ -926.185831 ┆ 27        ┆ высшее    ┆ … ┆ компаньон  ┆ 0    ┆ 255763.565 ┆ покупка    │
│          ┆             ┆           ┆           ┆   ┆            ┆      ┆ 419        ┆ жилья      │
│ 0        ┆ -2879.20205 ┆ 43        ┆ высшее    ┆ … ┆ компаньон  ┆ 0    ┆ 240525.971 ┆ операции с │
│          ┆ 2           ┆           ┆           ┆   ┆            ┆      ┆ 92         ┆ жильем     │
│ 0        ┆ -152.779569 ┆ 50        ┆ СРЕДНЕЕ   ┆ … ┆ сотрудник  ┆ 0    ┆ 135823.934 ┆ образовани │
│          ┆             ┆           ┆           ┆   ┆            ┆      ┆ 197        ┆ е          │
│ 2        ┆ -6929.86529 ┆ 35        ┆ ВЫСШЕЕ    ┆ … ┆ сотрудник  ┆ 0    ┆ 95856.8324 ┆ на         │
│          ┆ 9           ┆           ┆           ┆   ┆            ┆      ┆ 24         ┆ проведение │
│          ┆             ┆           ┆           ┆   ┆            ┆      ┆            ┆ свадьбы    │
│ 0        ┆ -2188.75644 ┆ 41        ┆ среднее   ┆ … ┆ сотрудник  ┆ 0    ┆ 144425.938 ┆ покупка    │
│          ┆ 5           ┆           ┆           ┆   ┆            ┆      ┆ 277        ┆ жилья для  │
│          ┆             ┆           ┆           ┆   ┆            ┆      ┆            ┆ семьи      │
└──────────┴─────────────┴───────────┴───────────┴───┴────────────┴──────┴────────────┴────────────┘

In [58]:
pl_info(df)

<class 'polars.DataFrame'>
RangeIndex: 0 to 21524 (21525 entries)
Columns: 12 entries
 #   Column               Non-Null Count  Dtype
---  -------------------- --------------  -----
  0  children             21525           Int64
  1  days_employed        19351           Float64
  2  dob_years            21525           Int64
  3  education            21525           String
  4  education_id         21525           Int64
  5  family_status        21525           String
  6  family_status_id     21525           Int64
  7  gender               21525           String
  8  income_type          21525           String
  9  debt                 21525           Int64
 10  total_income         19351           Float64
 11  purpose              21525           String
dtypes: Int64(5), Float64(2), String(5)
memory usage: 3.3 MB

**Выводы:**

1. В таблице 12 столбцов с типами `int64`, `float64`, `object`
2. Название колонок определены без стилистических нарушений:
    - Буквы в названиях приведены в одном регистре
    - Отсутсвуют пробелы
    - Название атрибутов в стиле snake_case
3. В столбцах есть пропущенные значения

## 3. Предобработка данных

### Обработка пропусков

#### Атрибут `children`

**1. Определение пропуска**

Первый не явный пропуск присутствует в атрибуте `children` - значение `-1`. Можно предположить, что это ошибка и убрать знак минуса перед числом. Можно и вовсе удалить эти строки, так как их объем довольно маленький 0.22% от общего кол-ва строк. Но в качестве упражнения заполним этот пропуск более корректными значениями.

In [61]:
print(f"Объем строк при 'children' равном -1: \
{(df.filter(pl.col('children') == -1).height / df.height)*100:0.2f}%")

df['children'].value_counts().sort('children')

Объем строк при 'children' равном -1: 0.22%

shape: (8, 2)
┌──────────┬───────┐
│ children ┆ count │
│ ---      ┆ ---   │
│ i64      ┆ u32   │
╞══════════╪═══════╡
│ -1       ┆ 47    │
│ 0        ┆ 14149 │
│ 1        ┆ 4818  │
│ 2        ┆ 2055  │
│ 3        ┆ 330   │
│ 4        ┆ 41    │
│ 5        ┆ 9     │
│ 20       ┆ 76    │
└──────────┴───────┘

**2. Определение типа пропуска**

Для определения типа пропусков в текущем атрибуте - сравним статистические характеристики следующих атрибутов при `children = -1` и `children != -1`:
- `dob_years`
- `education_id`
- `family_status_id`
- `gender`
- `income_type`

Первым рассмотрим атрибут `dob_years`, так как он, в отличии от остальных, имеет численный тип. По результатам ниже статистические характеристики данного атрибута практически не отличаются в зависимости от значения поля `children`.

In [21]:
print("Статистические характеристики атрибута 'dob_years': ", end='\n\n')
print("При 'children' равном -1:")
display(df.filter(pl.col('children') == -1).select(pl.col('dob_years')).describe());
print("При 'children' НЕ равном -1:")
display(df.filter(pl.col('children') != -1).select(pl.col('dob_years')).describe());

Статистические характеристики атрибута 'dob_years':

При 'children' равном -1:

shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ dob_years │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 47.0      │
│ null_count ┆ 0.0       │
│ mean       ┆ 42.574468 │
│ std        ┆ 11.357328 │
│ min        ┆ 23.0      │
│ 25%        ┆ 34.0      │
│ 50%        ┆ 41.0      │
│ 75%        ┆ 51.0      │
│ max        ┆ 69.0      │
└────────────┴───────────┘

При 'children' НЕ равном -1:

shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ dob_years │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 21478.0   │
│ null_count ┆ 0.0       │
│ mean       ┆ 43.294953 │
│ std        ┆ 12.577312 │
│ min        ┆ 0.0       │
│ 25%        ┆ 33.0      │
│ 50%        ┆ 42.0      │
│ 75%        ┆ 53.0      │
│ max        ┆ 75.0      │
└────────────┴───────────┘

Далее рассмотрим категориальные признаки - `gender`, `income_type`, `education_id`, `family_status_id`


Для категориальных атрибутов () следующего рода проверку - оценим отношение кол-ва каждого из значений вышеперечисленных атрибутов к общему числу строк в рассматриваемой группе и в случае, если в обеих группах строк эти отношения будут приблизительно равны, то значит содержание рассматриваемых атрибутов никак не влияет на некорректное заполнение атрибута  `children`.

Так как подобные манипуляции понадобятся для проверки пропусков и в других атрибутах, то напишем функцию которая будет вызывается с заданными параметрами.

In [65]:
value_counts_ratio(
    df=df,
    missing_filter_expr=(pl.col("children") == -1),
    columns_list=[
        "dob_years",
        "education",
        "family_status",
        "income_type"
    ]
)

1. Атрибут 'dob_years' — доля значений внутри группы, %:

shape: (88, 5)
┌──────────────────┬───────────┬───────┬────────────┬──────────┐
│ is_missing_group ┆ dob_years ┆ count ┆ group_size ┆ %        │
│ ---              ┆ ---       ┆ ---   ┆ ---        ┆ ---      │
│ bool             ┆ i64       ┆ u32   ┆ u32        ┆ f64      │
╞══════════════════╪═══════════╪═══════╪════════════╪══════════╡
│ false            ┆ 35        ┆ 616   ┆ 21478      ┆ 2.868051 │
│ false            ┆ 40        ┆ 607   ┆ 21478      ┆ 2.826148 │
│ false            ┆ 41        ┆ 605   ┆ 21478      ┆ 2.816836 │
│ false            ┆ 34        ┆ 600   ┆ 21478      ┆ 2.793556 │
│ false            ┆ 38        ┆ 596   ┆ 21478      ┆ 2.774932 │
│ false            ┆ 42        ┆ 595   ┆ 21478      ┆ 2.770277 │
│ false            ┆ 33        ┆ 579   ┆ 21478      ┆ 2.695782 │
│ false            ┆ 39        ┆ 573   ┆ 21478      ┆ 2.667846 │
│ false            ┆ 31        ┆ 558   ┆ 21478      ┆ 2.598007 │
│ false            ┆ 36        ┆ 555   ┆ 21478      ┆ 2.584039 │
│ …                ┆ …         ┆ …     ┆ …          ┆ …        │
│ true             ┆ 30        ┆ 1     ┆ 47         ┆ 2.12766  │
│ true             ┆ 51        ┆ 1     ┆ 47         ┆ 2.12766  │
│ true             ┆ 48        ┆ 1     ┆ 47         ┆ 2.12766  │
│ true             ┆ 23        ┆ 1     ┆ 47         ┆ 2.12766  │
│ true             ┆ 53        ┆ 1     ┆ 47         ┆ 2.12766  │
│ true             ┆ 26        ┆ 1     ┆ 47         ┆ 2.12766  │
│ true             ┆ 59        ┆ 1     ┆ 47         ┆ 2.12766  │
│ true             ┆ 64        ┆ 1     ┆ 47         ┆ 2.12766  │
│ true             ┆ 55        ┆ 1     ┆ 47         ┆ 2.12766  │
│ true             ┆ 27        ┆ 1     ┆ 47         ┆ 2.12766  │
└──────────────────┴───────────┴───────┴────────────┴──────────┘
====================================================================================================

2. Атрибут 'education' — доля значений внутри группы, %:

shape: (21, 5)
┌──────────────────┬─────────────────────┬───────┬────────────┬───────────┐
│ is_missing_group ┆ education           ┆ count ┆ group_size ┆ %         │
│ ---              ┆ ---                 ┆ ---   ┆ ---        ┆ ---       │
│ bool             ┆ str                 ┆ u32   ┆ u32        ┆ f64       │
╞══════════════════╪═════════════════════╪═══════╪════════════╪═══════════╡
│ false            ┆ среднее             ┆ 13719 ┆ 21478      ┆ 63.874662 │
│ false            ┆ высшее              ┆ 4710  ┆ 21478      ┆ 21.929416 │
│ false            ┆ СРЕДНЕЕ             ┆ 768   ┆ 21478      ┆ 3.575752  │
│ false            ┆ Среднее             ┆ 709   ┆ 21478      ┆ 3.301052  │
│ false            ┆ неоконченное высшее ┆ 667   ┆ 21478      ┆ 3.105503  │
│ false            ┆ ВЫСШЕЕ              ┆ 273   ┆ 21478      ┆ 1.271068  │
│ false            ┆ Высшее              ┆ 268   ┆ 21478      ┆ 1.247788  │
│ false            ┆ начальное           ┆ 250   ┆ 21478      ┆ 1.163982  │
│ false            ┆ Неоконченное высшее ┆ 47    ┆ 21478      ┆ 0.218829  │
│ false            ┆ НЕОКОНЧЕННОЕ ВЫСШЕЕ ┆ 29    ┆ 21478      ┆ 0.135022  │
│ …                ┆ …                   ┆ …     ┆ …          ┆ …         │
│ false            ┆ Начальное           ┆ 15    ┆ 21478      ┆ 0.069839  │
│ false            ┆ ученая степень      ┆ 4     ┆ 21478      ┆ 0.018624  │
│ false            ┆ УЧЕНАЯ СТЕПЕНЬ      ┆ 1     ┆ 21478      ┆ 0.004656  │
│ false            ┆ Ученая степень      ┆ 1     ┆ 21478      ┆ 0.004656  │
│ true             ┆ среднее             ┆ 31    ┆ 47         ┆ 65.957447 │
│ true             ┆ высшее              ┆ 8     ┆ 47         ┆ 17.021277 │
│ true             ┆ СРЕДНЕЕ             ┆ 4     ┆ 47         ┆ 8.510638  │
│ true             ┆ Среднее             ┆ 2     ┆ 47         ┆ 4.255319  │
│ true             ┆ ВЫСШЕЕ              ┆ 1     ┆ 47         ┆ 2.12766   │
│ true             ┆ неоконченное высшее ┆ 1     ┆ 47         ┆ 2.12766   │
└──────────────────┴─────────────────────┴───────┴────────────┴───────────┘
====================================================================================================

3. Атрибут 'family_status' — доля значений внутри группы, %:

shape: (10, 5)
┌──────────────────┬───────────────────────┬───────┬────────────┬───────────┐
│ is_missing_group ┆ family_status         ┆ count ┆ group_size ┆ %         │
│ ---              ┆ ---                   ┆ ---   ┆ ---        ┆ ---       │
│ bool             ┆ str                   ┆ u32   ┆ u32        ┆ f64       │
╞══════════════════╪═══════════════════════╪═══════╪════════════╪═══════════╡
│ false            ┆ женат / замужем       ┆ 12351 ┆ 21478      ┆ 57.505354 │
│ false            ┆ гражданский брак      ┆ 4172  ┆ 21478      ┆ 19.424527 │
│ false            ┆ Не женат / не замужем ┆ 2808  ┆ 21478      ┆ 13.073843 │
│ false            ┆ в разводе             ┆ 1191  ┆ 21478      ┆ 5.545209  │
│ false            ┆ вдовец / вдова        ┆ 956   ┆ 21478      ┆ 4.451066  │
│ true             ┆ женат / замужем       ┆ 29    ┆ 47         ┆ 61.702128 │
│ true             ┆ гражданский брак      ┆ 5     ┆ 47         ┆ 10.638298 │
│ true             ┆ Не женат / не замужем ┆ 5     ┆ 47         ┆ 10.638298 │
│ true             ┆ в разводе             ┆ 4     ┆ 47         ┆ 8.510638  │
│ true             ┆ вдовец / вдова        ┆ 4     ┆ 47         ┆ 8.510638  │
└──────────────────┴───────────────────────┴───────┴────────────┴───────────┘
====================================================================================================

4. Атрибут 'income_type' — доля значений внутри группы, %:

shape: (12, 5)
┌──────────────────┬─────────────────┬───────┬────────────┬───────────┐
│ is_missing_group ┆ income_type     ┆ count ┆ group_size ┆ %         │
│ ---              ┆ ---             ┆ ---   ┆ ---        ┆ ---       │
│ bool             ┆ str             ┆ u32   ┆ u32        ┆ f64       │
╞══════════════════╪═════════════════╪═══════╪════════════╪═══════════╡
│ false            ┆ сотрудник       ┆ 11093 ┆ 21478      ┆ 51.648198 │
│ false            ┆ компаньон       ┆ 5076  ┆ 21478      ┆ 23.633485 │
│ false            ┆ пенсионер       ┆ 3848  ┆ 21478      ┆ 17.916007 │
│ false            ┆ госслужащий     ┆ 1455  ┆ 21478      ┆ 6.774374  │
│ false            ┆ предприниматель ┆ 2     ┆ 21478      ┆ 0.009312  │
│ false            ┆ безработный     ┆ 2     ┆ 21478      ┆ 0.009312  │
│ false            ┆ студент         ┆ 1     ┆ 21478      ┆ 0.004656  │
│ false            ┆ в декрете       ┆ 1     ┆ 21478      ┆ 0.004656  │
│ true             ┆ сотрудник       ┆ 26    ┆ 47         ┆ 55.319149 │
│ true             ┆ компаньон       ┆ 9     ┆ 47         ┆ 19.148936 │
│ true             ┆ пенсионер       ┆ 8     ┆ 47         ┆ 17.021277 │
│ true             ┆ госслужащий     ┆ 4     ┆ 47         ┆ 8.510638  │
└──────────────────┴─────────────────┴───────┴────────────┴───────────┘
====================================================================================================

In [22]:
def value_counts_ration(missing_filter_expr, columns_list):
    """
    missing_filter_expr - выражение Polars для отбора строк с пропусками (например, pl.col('children') == -1)
    columns_list - список рассматриваемых атрибутов
    """
    curr_num = 0
    for curr_column in columns_list:
        curr_num += 1
        missing_group = df.filter(missing_filter_expr)
        filled_group = df.filter(~missing_filter_expr)
        missing_group_val_cnt = missing_group[curr_column].value_counts()
        filled_group_val_cnt = filled_group[curr_column].value_counts()
        missing_group_shape = missing_group.height
        filled_group_shape = filled_group.height
        print(f"{curr_num}. Атрибут '{curr_column}' - отношение кол-во каждого из его значений к общему числу строк, %:")
        print('')
        print(f"a. Группа строк с пропусками:\n{missing_group_val_cnt.with_columns((pl.col('count') / missing_group_shape * 100).alias('%'))}")
        print('')
        print(f"b. Группа строк заполненными значениями:\n{filled_group_val_cnt.with_columns((pl.col('count') / filled_group_shape * 100).alias('%'))}")
        print('='*100)
        print('')

Рассматриваемое отношение для обеих групп строк примерно одинаковые.

В группе строк с корректно заполненными значениями у некоторых атрибутов есть значения, которые отсутствуют в группе строк с пропусками, но так как их доля невелика, то они не влияют на появление пропусков - следовательно данные пропуски можно отнести к типу "Полностью случайные"

In [23]:
value_counts_ration(pl.col('children') == -1, ['gender', 'income_type', 'education_id', 'family_status_id'])

1. Атрибут 'gender' - отношение кол-во каждого из его значений к общему числу строк, %:

a. Группа строк с пропусками:
shape: (2, 3)
┌────────┬───────┬───────────┐
│ gender ┆ count ┆ %         │
│ ---    ┆ ---   ┆ ---       │
│ str    ┆ u32   ┆ f64       │
╞════════╪═══════╪═══════════╡
│ F      ┆ 35    ┆ 74.468085 │
│ M      ┆ 12    ┆ 25.531915 │
└────────┴───────┴───────────┘

b. Группа строк заполненными значениями:
shape: (3, 3)
┌────────┬───────┬───────────┐
│ gender ┆ count ┆ %         │
│ ---    ┆ ---   ┆ ---       │
│ str    ┆ u32   ┆ f64       │
╞════════╪═══════╪═══════════╡
│ M      ┆ 7276  ┆ 33.876525 │
│ F      ┆ 14201 ┆ 66.118819 │
│ XNA    ┆ 1     ┆ 0.004656  │
└────────┴───────┴───────────┘
====================================================================================================

2. Атрибут 'income_type' - отношение кол-во каждого из его значений к общему числу строк, %:

a. Группа строк с пропусками:
shape: (4, 3)
┌─────────────┬───────┬───────────┐
│ income_type ┆ count ┆ %         │
│ ---         ┆ ---   ┆ ---       │
│ str         ┆ u32   ┆ f64       │
╞═════════════╪═══════╪═══════════╡
│ пенсионер   ┆ 8     ┆ 17.021277 │
│ компаньон   ┆ 9     ┆ 19.148936 │
│ сотрудник   ┆ 26    ┆ 55.319149 │
│ госслужащий ┆ 4     ┆ 8.510638  │
└─────────────┴───────┴───────────┘

b. Группа строк заполненными значениями:
shape: (8, 3)
┌─────────────────┬───────┬───────────┐
│ income_type     ┆ count ┆ %         │
│ ---             ┆ ---   ┆ ---       │
│ str             ┆ u32   ┆ f64       │
╞═════════════════╪═══════╪═══════════╡
│ пенсионер       ┆ 3848  ┆ 17.916007 │
│ безработный     ┆ 2     ┆ 0.009312  │
│ в декрете       ┆ 1     ┆ 0.004656  │
│ компаньон       ┆ 5076  ┆ 23.633485 │
│ госслужащий     ┆ 1455  ┆ 6.774374  │
│ студент         ┆ 1     ┆ 0.004656  │
│ сотрудник       ┆ 11093 ┆ 51.648198 │
│ предприниматель ┆ 2     ┆ 0.009312  │
└─────────────────┴───────┴───────────┘
====================================================================================================

3. Атрибут 'education_id' - отношение кол-во каждого из его значений к общему числу строк, %:

a. Группа строк с пропусками:
shape: (3, 3)
┌──────────────┬───────┬───────────┐
│ education_id ┆ count ┆ %         │
│ ---          ┆ ---   ┆ ---       │
│ i64          ┆ u32   ┆ f64       │
╞══════════════╪═══════╪═══════════╡
│ 0            ┆ 9     ┆ 19.148936 │
│ 1            ┆ 37    ┆ 78.723404 │
│ 2            ┆ 1     ┆ 2.12766   │
└──────────────┴───────┴───────────┘

b. Группа строк заполненными значениями:
shape: (5, 3)
┌──────────────┬───────┬───────────┐
│ education_id ┆ count ┆ %         │
│ ---          ┆ ---   ┆ ---       │
│ i64          ┆ u32   ┆ f64       │
╞══════════════╪═══════╪═══════════╡
│ 3            ┆ 282   ┆ 1.312971  │
│ 2            ┆ 743   ┆ 3.459354  │
│ 0            ┆ 5251  ┆ 24.448273 │
│ 4            ┆ 6     ┆ 0.027936  │
│ 1            ┆ 15196 ┆ 70.751467 │
└──────────────┴───────┴───────────┘
====================================================================================================

4. Атрибут 'family_status_id' - отношение кол-во каждого из его значений к общему числу строк, %:

a. Группа строк с пропусками:
shape: (5, 3)
┌──────────────────┬───────┬───────────┐
│ family_status_id ┆ count ┆ %         │
│ ---              ┆ ---   ┆ ---       │
│ i64              ┆ u32   ┆ f64       │
╞══════════════════╪═══════╪═══════════╡
│ 0                ┆ 29    ┆ 61.702128 │
│ 2                ┆ 4     ┆ 8.510638  │
│ 4                ┆ 5     ┆ 10.638298 │
│ 1                ┆ 5     ┆ 10.638298 │
│ 3                ┆ 4     ┆ 8.510638  │
└──────────────────┴───────┴───────────┘

b. Группа строк заполненными значениями:
shape: (5, 3)
┌──────────────────┬───────┬───────────┐
│ family_status_id ┆ count ┆ %         │
│ ---              ┆ ---   ┆ ---       │
│ i64              ┆ u32   ┆ f64       │
╞══════════════════╪═══════╪═══════════╡
│ 2                ┆ 956   ┆ 4.451066  │
│ 4                ┆ 2808  ┆ 13.073843 │
│ 3                ┆ 1191  ┆ 5.545209  │
│ 0                ┆ 12351 ┆ 57.505354 │
│ 1                ┆ 4172  ┆ 19.424527 │
└──────────────────┴───────┴───────────┘
====================================================================================================

**Заполнение данных**

Так как в данных приведена информация о клиентах банка, то давайте попробуем их объединить в подгруппы по некоторыми признакам. Для каждой подгруппы посчитаем медианное значения кол-ва детей (т.к. медина устойчива к выбросам) и используем эти значения для корректировки некорректно заполненных строк.

Для того, чтобы определить перечень атрибутов, по которым стоит произвести группировку, поступим следующим образом - возьмем каждый рассматриваемый атрибут в отдельности, произведем группировку и посчитаем медианное значения для каждой полученной подгруппы. Используем группу строк с корректно заполненными значениями в атрибуте  `children`.

Рассматривать будем все те же атрибуты:
- `dob_years`
- `education_id`
- `family_status_id`
- `gender`
- `income_type`

В этом случае также напишем функцию, для дальнейшего применения.

In [24]:
def groupby_target_column_val(target_column, missing_filter_expr, columns_list):
    curr_num = 0
    filled_df = df.filter(~missing_filter_expr)
    for curr_column in columns_list:
        curr_num += 1
        med = filled_df.group_by(curr_column).agg(pl.col(target_column).median().round(2))
        print(f"{curr_num}. Атрибут {curr_column}\n{med}")
        print('='*100)
        print('')

Глядя на полученные результаты, можно сделать вывод, что группировку данных для заполнения пропущенных значения следует проводить только по атрибуту `dob_years`.

In [25]:
groupby_target_column_val('children', pl.col('children') == -1, ['dob_years', 'education_id',
                                                                  'family_status_id', 'gender',
                                                                  'income_type'])

1. Атрибут dob_years
shape: (58, 2)
┌───────────┬──────────┐
│ dob_years ┆ children │
│ ---       ┆ ---      │
│ i64       ┆ f64      │
╞═══════════╪══════════╡
│ 27        ┆ 0.0      │
│ 33        ┆ 1.0      │
│ 30        ┆ 1.0      │
│ 36        ┆ 1.0      │
│ 39        ┆ 1.0      │
│ 21        ┆ 0.0      │
│ 24        ┆ 0.0      │
│ 0         ┆ 0.0      │
│ 63        ┆ 0.0      │
│ 51        ┆ 0.0      │
│ …         ┆ …        │
│ 20        ┆ 0.0      │
│ 38        ┆ 1.0      │
│ 65        ┆ 0.0      │
│ 71        ┆ 0.0      │
│ 59        ┆ 0.0      │
│ 62        ┆ 0.0      │
│ 53        ┆ 0.0      │
│ 68        ┆ 0.0      │
│ 56        ┆ 0.0      │
│ 74        ┆ 0.0      │
└───────────┴──────────┘
====================================================================================================

2. Атрибут education_id
shape: (5, 2)
┌──────────────┬──────────┐
│ education_id ┆ children │
│ ---          ┆ ---      │
│ i64          ┆ f64      │
╞══════════════╪══════════╡
│ 0            ┆ 0.0      │
│ 3            ┆ 0.0      │
│ 4            ┆ 0.0      │
│ 1            ┆ 0.0      │
│ 2            ┆ 0.0      │
└──────────────┴──────────┘
====================================================================================================

3. Атрибут family_status_id
shape: (5, 2)
┌──────────────────┬──────────┐
│ family_status_id ┆ children │
│ ---              ┆ ---      │
│ i64              ┆ f64      │
╞══════════════════╪══════════╡
│ 3                ┆ 0.0      │
│ 0                ┆ 0.0      │
│ 4                ┆ 0.0      │
│ 1                ┆ 0.0      │
│ 2                ┆ 0.0      │
└──────────────────┴──────────┘
====================================================================================================

4. Атрибут gender
shape: (3, 2)
┌────────┬──────────┐
│ gender ┆ children │
│ ---    ┆ ---      │
│ str    ┆ f64      │
╞════════╪══════════╡
│ F      ┆ 0.0      │
│ XNA    ┆ 0.0      │
│ M      ┆ 0.0      │
└────────┴──────────┘
====================================================================================================

5. Атрибут income_type
shape: (8, 2)
┌─────────────────┬──────────┐
│ income_type     ┆ children │
│ ---             ┆ ---      │
│ str             ┆ f64      │
╞═════════════════╪══════════╡
│ сотрудник       ┆ 0.0      │
│ в декрете       ┆ 2.0      │
│ пенсионер       ┆ 0.0      │
│ госслужащий     ┆ 0.0      │
│ компаньон       ┆ 0.0      │
│ студент         ┆ 0.0      │
│ предприниматель ┆ 0.0      │
│ безработный     ┆ 0.5      │
└─────────────────┴──────────┘
====================================================================================================

Для этого напишем функциу, аналогичную функции из учебных материалов.

In [26]:
# Заполнение children: при children==-1 ставим 1 если 29<=dob_years<=40, иначе 0 (реализовано в следующей ячейке через when/then)

In [27]:
df = df.with_columns(
    pl.when(pl.col('children') == -1)
    .then(pl.when((pl.col('dob_years') >= 29) & (pl.col('dob_years') <= 40)).then(1).otherwise(0))
    .otherwise(pl.col('children'))
    .alias('children')
)

Проверим:

In [28]:
df['children'].value_counts().sort('children')

shape: (7, 2)
┌──────────┬───────┐
│ children ┆ count │
│ ---      ┆ ---   │
│ i64      ┆ u32   │
╞══════════╪═══════╡
│ 0        ┆ 14179 │
│ 1        ┆ 4835  │
│ 2        ┆ 2055  │
│ 3        ┆ 330   │
│ 4        ┆ 41    │
│ 5        ┆ 9     │
│ 20       ┆ 76    │
└──────────┴───────┘

#### Атрибут `dob_years`

Второй атрибут с некорретно заполнеными значениями является `dob_years`. В нем присудствуют 0-евые значения, но ведь возраст клиента не может равнятся 0.

Таких строк всего 0.47% от общего объема и можно от них избавиться, но давайте проведем анализ и постараемся скорректировать значения в этих строках.

In [29]:
print(f"Процент строк с некорректно заполненным атрибутом 'dob_years' - \
{(df.filter(pl.col('dob_years') == 0).height / df.height)*100:0.2f}%")

Процент строк с некорректно заполненным атрибутом 'dob_years' - 0.47%

**Определение типа пропусков** 

Для определения типа пропусков проведем все те же манипуляции, что и с атрибутом `children`. Только в этот раз рассмотрим следующие атрибуты:
- `children`
- `family_status_id`
- `gender`
- `income_type`

Рассматриваемое отношение для обеих групп строк примерно одинаковые.

В группе строк с корректно заполненными значениями у некоторых атрибутов есть значения, которые отсутствуют в группе строк с пропусками, но так как их доля невелика, то они не влияют на появление пропусков - следовательно данные пропуски можно отнести к типу "Полностью случайные".

In [30]:
value_counts_ration(pl.col('dob_years') == 0, ['children', 'family_status_id', 'gender', 'income_type'])

1. Атрибут 'children' - отношение кол-во каждого из его значений к общему числу строк, %:

a. Группа строк с пропусками:
shape: (5, 3)
┌──────────┬───────┬───────────┐
│ children ┆ count ┆ %         │
│ ---      ┆ ---   ┆ ---       │
│ i64      ┆ u32   ┆ f64       │
╞══════════╪═══════╪═══════════╡
│ 2        ┆ 13    ┆ 12.871287 │
│ 1        ┆ 16    ┆ 15.841584 │
│ 20       ┆ 1     ┆ 0.990099  │
│ 3        ┆ 2     ┆ 1.980198  │
│ 0        ┆ 69    ┆ 68.316832 │
└──────────┴───────┴───────────┘

b. Группа строк заполненными значениями:
shape: (7, 3)
┌──────────┬───────┬───────────┐
│ children ┆ count ┆ %         │
│ ---      ┆ ---   ┆ ---       │
│ i64      ┆ u32   ┆ f64       │
╞══════════╪═══════╪═══════════╡
│ 4        ┆ 41    ┆ 0.191374  │
│ 20       ┆ 75    ┆ 0.350075  │
│ 3        ┆ 328   ┆ 1.530993  │
│ 5        ┆ 9     ┆ 0.042009  │
│ 1        ┆ 4819  ┆ 22.493465 │
│ 0        ┆ 14110 ┆ 65.860717 │
│ 2        ┆ 2042  ┆ 9.531367  │
└──────────┴───────┴───────────┘
====================================================================================================

2. Атрибут 'family_status_id' - отношение кол-во каждого из его значений к общему числу строк, %:

a. Группа строк с пропусками:
shape: (5, 3)
┌──────────────────┬───────┬───────────┐
│ family_status_id ┆ count ┆ %         │
│ ---              ┆ ---   ┆ ---       │
│ i64              ┆ u32   ┆ f64       │
╞══════════════════╪═══════╪═══════════╡
│ 3                ┆ 10    ┆ 9.90099   │
│ 2                ┆ 5     ┆ 4.950495  │
│ 4                ┆ 16    ┆ 15.841584 │
│ 0                ┆ 49    ┆ 48.514851 │
│ 1                ┆ 21    ┆ 20.792079 │
└──────────────────┴───────┴───────────┘

b. Группа строк заполненными значениями:
shape: (5, 3)
┌──────────────────┬───────┬───────────┐
│ family_status_id ┆ count ┆ %         │
│ ---              ┆ ---   ┆ ---       │
│ i64              ┆ u32   ┆ f64       │
╞══════════════════╪═══════╪═══════════╡
│ 2                ┆ 955   ┆ 4.457618  │
│ 0                ┆ 12331 ┆ 57.556945 │
│ 4                ┆ 2797  ┆ 13.055452 │
│ 3                ┆ 1185  ┆ 5.53118   │
│ 1                ┆ 4156  ┆ 19.398805 │
└──────────────────┴───────┴───────────┘
====================================================================================================

3. Атрибут 'gender' - отношение кол-во каждого из его значений к общему числу строк, %:

a. Группа строк с пропусками:
shape: (2, 3)
┌────────┬───────┬───────────┐
│ gender ┆ count ┆ %         │
│ ---    ┆ ---   ┆ ---       │
│ str    ┆ u32   ┆ f64       │
╞════════╪═══════╪═══════════╡
│ M      ┆ 29    ┆ 28.712871 │
│ F      ┆ 72    ┆ 71.287129 │
└────────┴───────┴───────────┘

b. Группа строк заполненными значениями:
shape: (3, 3)
┌────────┬───────┬───────────┐
│ gender ┆ count ┆ %         │
│ ---    ┆ ---   ┆ ---       │
│ str    ┆ u32   ┆ f64       │
╞════════╪═══════╪═══════════╡
│ F      ┆ 14164 ┆ 66.112771 │
│ XNA    ┆ 1     ┆ 0.004668  │
│ M      ┆ 7259  ┆ 33.882562 │
└────────┴───────┴───────────┘
====================================================================================================

4. Атрибут 'income_type' - отношение кол-во каждого из его значений к общему числу строк, %:

a. Группа строк с пропусками:
shape: (4, 3)
┌─────────────┬───────┬───────────┐
│ income_type ┆ count ┆ %         │
│ ---         ┆ ---   ┆ ---       │
│ str         ┆ u32   ┆ f64       │
╞═════════════╪═══════╪═══════════╡
│ сотрудник   ┆ 55    ┆ 54.455446 │
│ пенсионер   ┆ 20    ┆ 19.80198  │
│ компаньон   ┆ 20    ┆ 19.80198  │
│ госслужащий ┆ 6     ┆ 5.940594  │
└─────────────┴───────┴───────────┘

b. Группа строк заполненными значениями:
shape: (8, 3)
┌─────────────────┬───────┬───────────┐
│ income_type     ┆ count ┆ %         │
│ ---             ┆ ---   ┆ ---       │
│ str             ┆ u32   ┆ f64       │
╞═════════════════╪═══════╪═══════════╡
│ студент         ┆ 1     ┆ 0.004668  │
│ компаньон       ┆ 5065  ┆ 23.64171  │
│ сотрудник       ┆ 11064 ┆ 51.643017 │
│ госслужащий     ┆ 1453  ┆ 6.782114  │
│ безработный     ┆ 2     ┆ 0.009335  │
│ пенсионер       ┆ 3836  ┆ 17.905153 │
│ в декрете       ┆ 1     ┆ 0.004668  │
│ предприниматель ┆ 2     ┆ 0.009335  │
└─────────────────┴───────┴───────────┘
====================================================================================================

**Заполнение данных**

Определим перечень атрибутов, по которым стоит произвести группировку.
Рассматривать будем все те же атрибуты:
- `children`
- `family_status_id`
- `gender`
- `income_type`

Группировку будем проводить по атрибуту `income_type`, так как по остальными атрибутам вариативность низкая.

In [31]:
groupby_target_column_val('dob_years', pl.col('dob_years') == 0, ['children', 'family_status_id',
                                                                   'gender', 'income_type'])

1. Атрибут children
shape: (7, 2)
┌──────────┬───────────┐
│ children ┆ dob_years │
│ ---      ┆ ---       │
│ i64      ┆ f64       │
╞══════════╪═══════════╡
│ 0        ┆ 48.0      │
│ 3        ┆ 36.0      │
│ 1        ┆ 38.0      │
│ 4        ┆ 35.0      │
│ 5        ┆ 36.0      │
│ 2        ┆ 35.0      │
│ 20       ┆ 42.0      │
└──────────┴───────────┘
====================================================================================================

2. Атрибут family_status_id
shape: (5, 2)
┌──────────────────┬───────────┐
│ family_status_id ┆ dob_years │
│ ---              ┆ ---       │
│ i64              ┆ f64       │
╞══════════════════╪═══════════╡
│ 3                ┆ 46.0      │
│ 0                ┆ 43.0      │
│ 1                ┆ 41.0      │
│ 4                ┆ 36.0      │
│ 2                ┆ 58.0      │
└──────────────────┴───────────┘
====================================================================================================

3. Атрибут gender
shape: (3, 2)
┌────────┬───────────┐
│ gender ┆ dob_years │
│ ---    ┆ ---       │
│ str    ┆ f64       │
╞════════╪═══════════╡
│ XNA    ┆ 24.0      │
│ F      ┆ 44.0      │
│ M      ┆ 40.0      │
└────────┴───────────┘
====================================================================================================

4. Атрибут income_type
shape: (8, 2)
┌─────────────────┬───────────┐
│ income_type     ┆ dob_years │
│ ---             ┆ ---       │
│ str             ┆ f64       │
╞═════════════════╪═══════════╡
│ сотрудник       ┆ 39.0      │
│ в декрете       ┆ 39.0      │
│ госслужащий     ┆ 40.0      │
│ пенсионер       ┆ 60.0      │
│ предприниматель ┆ 42.5      │
│ безработный     ┆ 38.0      │
│ студент         ┆ 22.0      │
│ компаньон       ┆ 39.0      │
└─────────────────┴───────────┘
====================================================================================================

Для этого напишем функциу, аналогичную функции из учебных материалов.

In [32]:
# Заполнение dob_years при значении 0 — по income_type (реализовано в следующей ячейке)

In [33]:
df = df.with_columns(
    pl.when(pl.col('dob_years') == 0)
    .then(
        pl.when(pl.col('income_type') == 'безработный').then(38)
        .when(pl.col('income_type').is_in(['в декрете', 'сотрудник', 'компаньон'])).then(39)
        .when(pl.col('income_type') == 'госслужащий').then(40)
        .when(pl.col('income_type') == 'пенсионер').then(60)
        .when(pl.col('income_type') == 'предприниматель').then(43)
        .when(pl.col('income_type') == 'студент').then(22)
        .otherwise(pl.col('dob_years'))
    )
    .otherwise(pl.col('dob_years'))
    .alias('dob_years')
)

Проверим:

In [34]:
df.filter(pl.col('dob_years') == 0)

shape: (0, 12)
┌──────────┬──────────────┬───────────┬───────────┬───┬─────────────┬──────┬─────────────┬─────────┐
│ children ┆ days_employe ┆ dob_years ┆ education ┆ … ┆ income_type ┆ debt ┆ total_incom ┆ purpose │
│ ---      ┆ d            ┆ ---       ┆ ---       ┆   ┆ ---         ┆ ---  ┆ e           ┆ ---     │
│ i64      ┆ ---          ┆ i64       ┆ str       ┆   ┆ str         ┆ i64  ┆ ---         ┆ str     │
│          ┆ f64          ┆           ┆           ┆   ┆             ┆      ┆ f64         ┆         │
╞══════════╪══════════════╪═══════════╪═══════════╪═══╪═════════════╪══════╪═════════════╪═════════╡
└──────────┴──────────────┴───────────┴───────────┴───┴─────────────┴──────┴─────────────┴─────────┘

#### Атрибут `gender`

Строку, которая содержит значения "XNA" в атрибуте `gender` просто удалим, так как она всего одна.

In [35]:
df.filter(pl.col('gender') == 'XNA')

shape: (1, 12)
┌──────────┬────────────┬───────────┬────────────┬───┬────────────┬──────┬────────────┬────────────┐
│ children ┆ days_emplo ┆ dob_years ┆ education  ┆ … ┆ income_typ ┆ debt ┆ total_inco ┆ purpose    │
│ ---      ┆ yed        ┆ ---       ┆ ---        ┆   ┆ e          ┆ ---  ┆ me         ┆ ---        │
│ i64      ┆ ---        ┆ i64       ┆ str        ┆   ┆ ---        ┆ i64  ┆ ---        ┆ str        │
│          ┆ f64        ┆           ┆            ┆   ┆ str        ┆      ┆ f64        ┆            │
╞══════════╪════════════╪═══════════╪════════════╪═══╪════════════╪══════╪════════════╪════════════╡
│ 0        ┆ -2358.6005 ┆ 24        ┆ неоконченн ┆ … ┆ компаньон  ┆ 0    ┆ 203905.157 ┆ покупка    │
│          ┆ 02         ┆           ┆ ое высшее  ┆   ┆            ┆      ┆ 261        ┆ недвижимос │
│          ┆            ┆           ┆            ┆   ┆            ┆      ┆            ┆ ти         │
└──────────┴────────────┴───────────┴────────────┴───┴────────────┴──────┴────────────┴────────────┘

In [36]:
# Удаляем строки, в которых атрибут gender принимает значение 'XNA'
df = df.filter(pl.col('gender') != 'XNA')

#### Атрибут `days_employed`

Перед тем как определить тип пропусков и способ его заполнения приведем значения в данном атрибуте в единый формат.

1. В атрибуте есть положительные и отрицательные числа
2. Название атрибута предполагает содержание кол-ва дней, но:
    - только отрицательные числа приведены в днях
    - положительные в часах

In [37]:
# Отрицательные — в днях, положительные — переводим из часов в дни (делим на 24), затем abs и round
df = df.with_columns(
    pl.when(pl.col('days_employed') < 0)
    .then(pl.col('days_employed').abs())
    .otherwise(pl.col('days_employed') / 24)
    .abs()
    .round(2)
    .alias('days_employed')
)
df['days_employed']

shape: (21_524,)
Series: 'days_employed' [f64]
[
	8437.67
	4024.8
	5623.42
	4124.75
	14177.75
	926.19
	2879.2
	152.78
	6929.87
	2188.76
	…
	467.69
	914.39
	404.68
	15583.15
	2351.43
	4529.32
	14330.73
	2113.35
	3112.48
	1984.51
]

Оценим объем пропущенных данные в атрибуте `days_employed`.
Он составляет 10.1% от общего кол-ва строк

In [38]:
print(f"Процент строк с не заполненным атрибутом 'days_employed' - \
{(df.filter(pl.col('days_employed').is_null()).height / df.height)*100:0.2f}%")

Процент строк с не заполненным атрибутом 'days_employed' - 10.10%

**Определение типа пропусков** 

Потенциально на кол-во детей могут повлиять характеристики по следующим атрибутам - `dob_years`, `education_id`, `family_status_id`.

Сравним статистические характеристики атрибута `dob_years` при пропущенных и заполненных значениях.

Как мы видим, для обоих группу строк статистические характеристики данного атрибута не сильно отличаются.

In [39]:
print("Статистические характеристики атрибута 'dob_years': ")
print('')
print("1. Группа строк с пропусками:")
print(df.filter(pl.col('days_employed').is_null()).select(pl.col('dob_years')).describe())
print('')
print("2. Группа строк с заполненными значениями:")
print(df.filter(pl.col('days_employed').is_not_null()).select(pl.col('dob_years')).describe())

Статистические характеристики атрибута 'dob_years':

1. Группа строк с пропусками:
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ dob_years │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 2174.0    │
│ null_count ┆ 0.0       │
│ mean       ┆ 43.840386 │
│ std        ┆ 12.193138 │
│ min        ┆ 19.0      │
│ 25%        ┆ 34.0      │
│ 50%        ┆ 43.0      │
│ 75%        ┆ 54.0      │
│ max        ┆ 73.0      │
└────────────┴───────────┘

2. Группа строк с заполненными значениями:
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ dob_years │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 19350.0   │
│ null_count ┆ 0.0       │
│ mean       ┆ 43.458501 │
│ std        ┆ 12.23507  │
│ min        ┆ 19.0      │
│ 25%        ┆ 33.0      │
│ 50%        ┆ 42.0      │
│ 75%        ┆ 53.0      │
│ max        ┆ 75.0      │
└────────────┴───────────┘

Сравним кол-во значений в атрибутах `gender`, `income_type`, `education_id`, `family_status_id`.

Рассматриваемое отношение для обеих групп строк примерно одинаковые.

В группе строк с корректно заполненными значениями у некоторых атрибутов есть значения, которые отсутствуют в группе строк с пропусками, но так как их доля невелика, то они не влияют на появление пропусков - следовательно данные пропуски можно отнести к типу "Полностью случайные".

In [40]:
value_counts_ration(pl.col('days_employed').is_null(), ['gender', 'income_type', 'education_id', 'family_status_id'])

1. Атрибут 'gender' - отношение кол-во каждого из его значений к общему числу строк, %:

a. Группа строк с пропусками:
shape: (2, 3)
┌────────┬───────┬──────────┐
│ gender ┆ count ┆ %        │
│ ---    ┆ ---   ┆ ---      │
│ str    ┆ u32   ┆ f64      │
╞════════╪═══════╪══════════╡
│ F      ┆ 1484  ┆ 68.26127 │
│ M      ┆ 690   ┆ 31.73873 │
└────────┴───────┴──────────┘

b. Группа строк заполненными значениями:
shape: (2, 3)
┌────────┬───────┬───────────┐
│ gender ┆ count ┆ %         │
│ ---    ┆ ---   ┆ ---       │
│ str    ┆ u32   ┆ f64       │
╞════════╪═══════╪═══════════╡
│ M      ┆ 6598  ┆ 34.098191 │
│ F      ┆ 12752 ┆ 65.901809 │
└────────┴───────┴───────────┘
====================================================================================================

2. Атрибут 'income_type' - отношение кол-во каждого из его значений к общему числу строк, %:

a. Группа строк с пропусками:
shape: (5, 3)
┌─────────────────┬───────┬───────────┐
│ income_type     ┆ count ┆ %         │
│ ---             ┆ ---   ┆ ---       │
│ str             ┆ u32   ┆ f64       │
╞═════════════════╪═══════╪═══════════╡
│ сотрудник       ┆ 1105  ┆ 50.827967 │
│ предприниматель ┆ 1     ┆ 0.045998  │
│ компаньон       ┆ 508   ┆ 23.367065 │
│ госслужащий     ┆ 147   ┆ 6.76173   │
│ пенсионер       ┆ 413   ┆ 18.99724  │
└─────────────────┴───────┴───────────┘

b. Группа строк заполненными значениями:
shape: (8, 3)
┌─────────────────┬───────┬───────────┐
│ income_type     ┆ count ┆ %         │
│ ---             ┆ ---   ┆ ---       │
│ str             ┆ u32   ┆ f64       │
╞═════════════════╪═══════╪═══════════╡
│ студент         ┆ 1     ┆ 0.005168  │
│ предприниматель ┆ 1     ┆ 0.005168  │
│ безработный     ┆ 2     ┆ 0.010336  │
│ пенсионер       ┆ 3443  ┆ 17.793282 │
│ компаньон       ┆ 4576  ┆ 23.648579 │
│ госслужащий     ┆ 1312  ┆ 6.780362  │
│ в декрете       ┆ 1     ┆ 0.005168  │
│ сотрудник       ┆ 10014 ┆ 51.751938 │
└─────────────────┴───────┴───────────┘
====================================================================================================

3. Атрибут 'education_id' - отношение кол-во каждого из его значений к общему числу строк, %:

a. Группа строк с пропусками:
shape: (4, 3)
┌──────────────┬───────┬───────────┐
│ education_id ┆ count ┆ %         │
│ ---          ┆ ---   ┆ ---       │
│ i64          ┆ u32   ┆ f64       │
╞══════════════╪═══════╪═══════════╡
│ 0            ┆ 544   ┆ 25.022999 │
│ 3            ┆ 21    ┆ 0.965961  │
│ 1            ┆ 1540  ┆ 70.837167 │
│ 2            ┆ 69    ┆ 3.173873  │
└──────────────┴───────┴───────────┘

b. Группа строк заполненными значениями:
shape: (5, 3)
┌──────────────┬───────┬───────────┐
│ education_id ┆ count ┆ %         │
│ ---          ┆ ---   ┆ ---       │
│ i64          ┆ u32   ┆ f64       │
╞══════════════╪═══════╪═══════════╡
│ 0            ┆ 4716  ┆ 24.372093 │
│ 2            ┆ 674   ┆ 3.483204  │
│ 3            ┆ 261   ┆ 1.348837  │
│ 4            ┆ 6     ┆ 0.031008  │
│ 1            ┆ 13693 ┆ 70.764858 │
└──────────────┴───────┴───────────┘
====================================================================================================

4. Атрибут 'family_status_id' - отношение кол-во каждого из его значений к общему числу строк, %:

a. Группа строк с пропусками:
shape: (5, 3)
┌──────────────────┬───────┬───────────┐
│ family_status_id ┆ count ┆ %         │
│ ---              ┆ ---   ┆ ---       │
│ i64              ┆ u32   ┆ f64       │
╞══════════════════╪═══════╪═══════════╡
│ 2                ┆ 95    ┆ 4.369825  │
│ 4                ┆ 288   ┆ 13.24747  │
│ 3                ┆ 112   ┆ 5.151794  │
│ 1                ┆ 442   ┆ 20.331187 │
│ 0                ┆ 1237  ┆ 56.899724 │
└──────────────────┴───────┴───────────┘

b. Группа строк заполненными значениями:
shape: (5, 3)
┌──────────────────┬───────┬───────────┐
│ family_status_id ┆ count ┆ %         │
│ ---              ┆ ---   ┆ ---       │
│ i64              ┆ u32   ┆ f64       │
╞══════════════════╪═══════╪═══════════╡
│ 0                ┆ 11143 ┆ 57.586563 │
│ 3                ┆ 1083  ┆ 5.596899  │
│ 2                ┆ 865   ┆ 4.470284  │
│ 4                ┆ 2525  ┆ 13.049096 │
│ 1                ┆ 3734  ┆ 19.297158 │
└──────────────────┴───────┴───────────┘
====================================================================================================

**Заполнение данных**

Определим перечень атрибутов, по которым стоит произвести группировку.
Рассматривать будем все те же атрибуты:
- `gender`
- `income_type`
- `education_id`
- `family_status_id`

In [41]:
groupby_target_column_val('days_employed', pl.col('days_employed').is_null(), ['dob_years', 'education_id',
                                                                                'family_status_id', 'gender',
                                                                                'income_type'])

1. Атрибут dob_years
shape: (57, 2)
┌───────────┬───────────────┐
│ dob_years ┆ days_employed │
│ ---       ┆ ---           │
│ i64       ┆ f64           │
╞═══════════╪═══════════════╡
│ 24        ┆ 942.39        │
│ 36        ┆ 1799.52       │
│ 27        ┆ 1166.21       │
│ 30        ┆ 1420.59       │
│ 33        ┆ 1426.42       │
│ 21        ┆ 618.73        │
│ 39        ┆ 1766.84       │
│ 63        ┆ 14936.77      │
│ 60        ┆ 14580.54      │
│ 72        ┆ 15307.46      │
│ …         ┆ …             │
│ 44        ┆ 2084.33       │
│ 50        ┆ 2626.99       │
│ 65        ┆ 14902.85      │
│ 59        ┆ 14417.11      │
│ 71        ┆ 14987.54      │
│ 53        ┆ 3650.01       │
│ 56        ┆ 6850.18       │
│ 74        ┆ 14294.84      │
│ 68        ┆ 15219.93      │
│ 62        ┆ 14790.91      │
└───────────┴───────────────┘
====================================================================================================

2. Атрибут education_id
shape: (5, 2)
┌──────────────┬───────────────┐
│ education_id ┆ days_employed │
│ ---          ┆ ---           │
│ i64          ┆ f64           │
╞══════════════╪═══════════════╡
│ 0            ┆ 1895.75       │
│ 3            ┆ 3043.93       │
│ 4            ┆ 5660.06       │
│ 1            ┆ 2392.48       │
│ 2            ┆ 1206.48       │
└──────────────┴───────────────┘
====================================================================================================

3. Атрибут family_status_id
shape: (5, 2)
┌──────────────────┬───────────────┐
│ family_status_id ┆ days_employed │
│ ---              ┆ ---           │
│ i64              ┆ f64           │
╞══════════════════╪═══════════════╡
│ 0                ┆ 2304.96       │
│ 3                ┆ 2401.95       │
│ 4                ┆ 1462.01       │
│ 1                ┆ 1944.0        │
│ 2                ┆ 14053.62      │
└──────────────────┴───────────────┘
====================================================================================================

4. Атрибут gender
shape: (2, 2)
┌────────┬───────────────┐
│ gender ┆ days_employed │
│ ---    ┆ ---           │
│ str    ┆ f64           │
╞════════╪═══════════════╡
│ M      ┆ 1662.37       │
│ F      ┆ 2539.86       │
└────────┴───────────────┘
====================================================================================================

5. Атрибут income_type
shape: (8, 2)
┌─────────────────┬───────────────┐
│ income_type     ┆ days_employed │
│ ---             ┆ ---           │
│ str             ┆ f64           │
╞═════════════════╪═══════════════╡
│ госслужащий     ┆ 2689.37       │
│ компаньон       ┆ 1546.33       │
│ безработный     ┆ 15267.24      │
│ сотрудник       ┆ 1574.21       │
│ предприниматель ┆ 520.85        │
│ в декрете       ┆ 3296.76       │
│ студент         ┆ 578.75        │
│ пенсионер       ┆ 15217.22      │
└─────────────────┴───────────────┘
====================================================================================================

Сильной вариативности медианного значения `dob_years` в атрибутах `family_status_id` и `education_id` - нет. Поэтому не будет учитывать их при группировке данных.

Чем больше атрибутов, по которым производится группировка, тем больше подгрупп данных с пустыми медийными значениями.

In [42]:
# Сгруппируем данные по выбранным атрибутам и посчитаем медиану для каждой подгруппы
temp_group_df = (
    df.select(['gender', 'income_type', 'dob_years', 'days_employed'])
    .group_by(['gender', 'income_type', 'dob_years'])
    .agg(pl.col('days_employed').median().alias('days_employed_median'))
)
temp_group_df.filter(pl.col('days_employed_median').is_null()).shape

(5, 4)

Так как атрибутов по которым проводится группировка много, то не будем писать функцию на подобии `dob_years_group_children_cnt`, а поступим иначе.

In [43]:
# Соединяем df с temp_group_df по ключам (left join)
df = df.join(temp_group_df, on=['gender', 'income_type', 'dob_years'], how='left')
# Заполняем пропуски в days_employed медианой по группе
df = df.with_columns(
    pl.when(pl.col('days_employed').is_null())
    .then(pl.col('days_employed_median'))
    .otherwise(pl.col('days_employed'))
    .alias('days_employed')
)

Проверим. Остлось пять строк, которые относятся к подгруппе для которых не удалось посчитать меданное значение `days_employed`. Их всего 5 шт. - удалим их.

In [44]:
df.filter(pl.col('days_employed').is_null())

shape: (5, 13)
┌──────────┬─────────────┬───────────┬───────────┬───┬──────┬────────────┬────────────┬────────────┐
│ children ┆ days_employ ┆ dob_years ┆ education ┆ … ┆ debt ┆ total_inco ┆ purpose    ┆ days_emplo │
│ ---      ┆ ed          ┆ ---       ┆ ---       ┆   ┆ ---  ┆ me         ┆ ---        ┆ yed_median │
│ i64      ┆ ---         ┆ i64       ┆ str       ┆   ┆ i64  ┆ ---        ┆ str        ┆ ---        │
│          ┆ f64         ┆           ┆           ┆   ┆      ┆ f64        ┆            ┆ f64        │
╞══════════╪═════════════╪═══════════╪═══════════╪═══╪══════╪════════════╪════════════╪════════════╡
│ 0        ┆ null        ┆ 24        ┆ среднее   ┆ … ┆ 0    ┆ null       ┆ покупка    ┆ null       │
│          ┆             ┆           ┆           ┆   ┆      ┆            ┆ своего     ┆            │
│          ┆             ┆           ┆           ┆   ┆      ┆            ┆ жилья      ┆            │
│ 0        ┆ null        ┆ 58        ┆ высшее    ┆ … ┆ 0    ┆ null       ┆ покупка    ┆ null       │
│          ┆             ┆           ┆           ┆   ┆      ┆            ┆ жилой недв ┆            │
│          ┆             ┆           ┆           ┆   ┆      ┆            ┆ ижимости   ┆            │
│ 0        ┆ null        ┆ 69        ┆ высшее    ┆ … ┆ 0    ┆ null       ┆ автомобили ┆ null       │
│ 2        ┆ null        ┆ 31        ┆ среднее   ┆ … ┆ 0    ┆ null       ┆ свадьба    ┆ null       │
│ 0        ┆ null        ┆ 38        ┆ среднее   ┆ … ┆ 0    ┆ null       ┆ профильное ┆ null       │
│          ┆             ┆           ┆           ┆   ┆      ┆            ┆ образовани ┆            │
│          ┆             ┆           ┆           ┆   ┆      ┆            ┆ е          ┆            │
└──────────┴─────────────┴───────────┴───────────┴───┴──────┴────────────┴────────────┴────────────┘

In [45]:
# Удаляем строки с пропусками в days_employed
df = df.filter(pl.col('days_employed').is_not_null())

In [46]:
# Удаляем столбец days_employed_median и переменную temp_group_df
df = df.drop('days_employed_median')
del temp_group_df

In [47]:
# Округляем days_employed до целого (дни)
df = df.with_columns(pl.col('days_employed').round().alias('days_employed'))

#### Атрибут `total_income`

Оценим объем пропущенных данные в атрибуте `days_employed`.
Он составляет 10.8% от общего кол-ва строк.

In [48]:
print(f"Процент строк с не заполненным атрибутом 'total_income' - \
{(df.filter(pl.col('total_income').is_null()).height / df.height)*100:0.2f}%")

Процент строк с не заполненным атрибутом 'total_income' - 10.08%

**Определение типа пропусков** 

Потенциально на кол-во детей могут повлиять характеристики по следующим атрибутам - `dob_years`, `education_id`, `family_status_id`.

Сравним статистические характеристики атрибута `dob_years` при пропущенных и заполненных значениях.

Как мы видим, для обоих группу строк статистические характеристики данного атрибута не сильно отличаются.

In [49]:
print("Статистические характеристики атрибута 'dob_years': ")
print('')
print("1. Группа строк с пропусками в total_income:")
print(df.filter(pl.col('total_income').is_null()).select(pl.col('dob_years')).describe())
print('')
print("2. Группа строк с заполненными значениями:")
print(df.filter(pl.col('total_income').is_not_null()).select(pl.col('dob_years')).describe())

Статистические характеристики атрибута 'dob_years':

1. Группа строк с пропусками в total_income:
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ dob_years │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 2169.0    │
│ null_count ┆ 0.0       │
│ mean       ┆ 43.840018 │
│ std        ┆ 12.180217 │
│ min        ┆ 19.0      │
│ 25%        ┆ 34.0      │
│ 50%        ┆ 43.0      │
│ 75%        ┆ 54.0      │
│ max        ┆ 73.0      │
└────────────┴───────────┘

2. Группа строк с заполненными значениями:
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ dob_years │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 19350.0   │
│ null_count ┆ 0.0       │
│ mean       ┆ 43.458501 │
│ std        ┆ 12.23507  │
│ min        ┆ 19.0      │
│ 25%        ┆ 33.0      │
│ 50%        ┆ 42.0      │
│ 75%        ┆ 53.0      │
│ max        ┆ 75.0      │
└────────────┴───────────┘

Сравним кол-во значений в атрибутах `gender`, `income_type`, `education_id`, `family_status_id`.

Рассматриваемое отношение для обеих групп строк примерно одинаковые.

В группе строк с корректно заполненными значениями у некоторых атрибутов есть значения, которые отсутствуют в группе строк с пропусками, но так как их доля невелика, то они не влияют на появление пропусков - следовательно данные пропуски можно отнести к типу "Полностью случайные".

In [50]:
value_counts_ration(pl.col('total_income').is_null(), ['gender', 'income_type', 'education_id', 'family_status_id'])

1. Атрибут 'gender' - отношение кол-во каждого из его значений к общему числу строк, %:

a. Группа строк с пропусками:
shape: (2, 3)
┌────────┬───────┬───────────┐
│ gender ┆ count ┆ %         │
│ ---    ┆ ---   ┆ ---       │
│ str    ┆ u32   ┆ f64       │
╞════════╪═══════╪═══════════╡
│ M      ┆ 688   ┆ 31.719686 │
│ F      ┆ 1481  ┆ 68.280314 │
└────────┴───────┴───────────┘

b. Группа строк заполненными значениями:
shape: (2, 3)
┌────────┬───────┬───────────┐
│ gender ┆ count ┆ %         │
│ ---    ┆ ---   ┆ ---       │
│ str    ┆ u32   ┆ f64       │
╞════════╪═══════╪═══════════╡
│ F      ┆ 12752 ┆ 65.901809 │
│ M      ┆ 6598  ┆ 34.098191 │
└────────┴───────┴───────────┘
====================================================================================================

2. Атрибут 'income_type' - отношение кол-во каждого из его значений к общему числу строк, %:

a. Группа строк с пропусками:
shape: (4, 3)
┌─────────────┬───────┬───────────┐
│ income_type ┆ count ┆ %         │
│ ---         ┆ ---   ┆ ---       │
│ str         ┆ u32   ┆ f64       │
╞═════════════╪═══════╪═══════════╡
│ пенсионер   ┆ 410   ┆ 18.90272  │
│ компаньон   ┆ 507   ┆ 23.374827 │
│ госслужащий ┆ 147   ┆ 6.777317  │
│ сотрудник   ┆ 1105  ┆ 50.945136 │
└─────────────┴───────┴───────────┘

b. Группа строк заполненными значениями:
shape: (8, 3)
┌─────────────────┬───────┬───────────┐
│ income_type     ┆ count ┆ %         │
│ ---             ┆ ---   ┆ ---       │
│ str             ┆ u32   ┆ f64       │
╞═════════════════╪═══════╪═══════════╡
│ сотрудник       ┆ 10014 ┆ 51.751938 │
│ госслужащий     ┆ 1312  ┆ 6.780362  │
│ пенсионер       ┆ 3443  ┆ 17.793282 │
│ компаньон       ┆ 4576  ┆ 23.648579 │
│ в декрете       ┆ 1     ┆ 0.005168  │
│ предприниматель ┆ 1     ┆ 0.005168  │
│ студент         ┆ 1     ┆ 0.005168  │
│ безработный     ┆ 2     ┆ 0.010336  │
└─────────────────┴───────┴───────────┘
====================================================================================================

3. Атрибут 'education_id' - отношение кол-во каждого из его значений к общему числу строк, %:

a. Группа строк с пропусками:
shape: (4, 3)
┌──────────────┬───────┬───────────┐
│ education_id ┆ count ┆ %         │
│ ---          ┆ ---   ┆ ---       │
│ i64          ┆ u32   ┆ f64       │
╞══════════════╪═══════╪═══════════╡
│ 0            ┆ 542   ┆ 24.988474 │
│ 1            ┆ 1537  ┆ 70.862148 │
│ 2            ┆ 69    ┆ 3.181189  │
│ 3            ┆ 21    ┆ 0.968188  │
└──────────────┴───────┴───────────┘

b. Группа строк заполненными значениями:
shape: (5, 3)
┌──────────────┬───────┬───────────┐
│ education_id ┆ count ┆ %         │
│ ---          ┆ ---   ┆ ---       │
│ i64          ┆ u32   ┆ f64       │
╞══════════════╪═══════╪═══════════╡
│ 4            ┆ 6     ┆ 0.031008  │
│ 3            ┆ 261   ┆ 1.348837  │
│ 2            ┆ 674   ┆ 3.483204  │
│ 1            ┆ 13693 ┆ 70.764858 │
│ 0            ┆ 4716  ┆ 24.372093 │
└──────────────┴───────┴───────────┘
====================================================================================================

4. Атрибут 'family_status_id' - отношение кол-во каждого из его значений к общему числу строк, %:

a. Группа строк с пропусками:
shape: (5, 3)
┌──────────────────┬───────┬───────────┐
│ family_status_id ┆ count ┆ %         │
│ ---              ┆ ---   ┆ ---       │
│ i64              ┆ u32   ┆ f64       │
╞══════════════════╪═══════╪═══════════╡
│ 1                ┆ 440   ┆ 20.285846 │
│ 0                ┆ 1235  ┆ 56.938681 │
│ 3                ┆ 112   ┆ 5.16367   │
│ 4                ┆ 287   ┆ 13.231904 │
│ 2                ┆ 95    ┆ 4.379899  │
└──────────────────┴───────┴───────────┘

b. Группа строк заполненными значениями:
shape: (5, 3)
┌──────────────────┬───────┬───────────┐
│ family_status_id ┆ count ┆ %         │
│ ---              ┆ ---   ┆ ---       │
│ i64              ┆ u32   ┆ f64       │
╞══════════════════╪═══════╪═══════════╡
│ 4                ┆ 2525  ┆ 13.049096 │
│ 3                ┆ 1083  ┆ 5.596899  │
│ 2                ┆ 865   ┆ 4.470284  │
│ 1                ┆ 3734  ┆ 19.297158 │
│ 0                ┆ 11143 ┆ 57.586563 │
└──────────────────┴───────┴───────────┘
====================================================================================================

**Заполнение данных**

Определим перечень атрибутов, по которым стоит произвести группировку.
Рассматривать будем все те же атрибуты:
- `gender`
- `income_type`
- `education_id`
- `family_status_id`

In [51]:
groupby_target_column_val('total_income', pl.col('total_income').is_null(), ['dob_years', 'education_id',
                                                                            'family_status_id', 'gender',
                                                                            'income_type'])

1. Атрибут dob_years
shape: (57, 2)
┌───────────┬──────────────┐
│ dob_years ┆ total_income │
│ ---       ┆ ---          │
│ i64       ┆ f64          │
╞═══════════╪══════════════╡
│ 39        ┆ 150118.19    │
│ 30        ┆ 146944.67    │
│ 27        ┆ 154429.25    │
│ 21        ┆ 128265.72    │
│ 33        ┆ 156538.85    │
│ 36        ┆ 158681.48    │
│ 24        ┆ 140381.59    │
│ 51        ┆ 145132.36    │
│ 42        ┆ 159167.99    │
│ 72        ┆ 110985.53    │
│ …         ┆ …            │
│ 32        ┆ 151253.91    │
│ 44        ┆ 152302.9     │
│ 56        ┆ 139119.71    │
│ 65        ┆ 122934.15    │
│ 71        ┆ 122934.29    │
│ 62        ┆ 132382.91    │
│ 59        ┆ 136854.84    │
│ 68        ┆ 113208.39    │
│ 53        ┆ 140999.06    │
│ 74        ┆ 76850.33     │
└───────────┴──────────────┘
====================================================================================================

2. Атрибут education_id
shape: (5, 2)
┌──────────────┬──────────────┐
│ education_id ┆ total_income │
│ ---          ┆ ---          │
│ i64          ┆ f64          │
╞══════════════╪══════════════╡
│ 3            ┆ 117137.35    │
│ 0            ┆ 175340.82    │
│ 4            ┆ 157259.9     │
│ 1            ┆ 136478.64    │
│ 2            ┆ 160054.97    │
└──────────────┴──────────────┘
====================================================================================================

3. Атрибут family_status_id
shape: (5, 2)
┌──────────────────┬──────────────┐
│ family_status_id ┆ total_income │
│ ---              ┆ ---          │
│ i64              ┆ f64          │
╞══════════════════╪══════════════╡
│ 0                ┆ 146184.63    │
│ 3                ┆ 146969.35    │
│ 1                ┆ 144909.23    │
│ 4                ┆ 144681.42    │
│ 2                ┆ 128213.69    │
└──────────────────┴──────────────┘
====================================================================================================

4. Атрибут gender
shape: (2, 2)
┌────────┬──────────────┐
│ gender ┆ total_income │
│ ---    ┆ ---          │
│ str    ┆ f64          │
╞════════╪══════════════╡
│ F      ┆ 134155.28    │
│ M      ┆ 167714.34    │
└────────┴──────────────┘
====================================================================================================

5. Атрибут income_type
shape: (8, 2)
┌─────────────────┬──────────────┐
│ income_type     ┆ total_income │
│ ---             ┆ ---          │
│ str             ┆ f64          │
╞═════════════════╪══════════════╡
│ безработный     ┆ 131339.75    │
│ пенсионер       ┆ 118514.49    │
│ компаньон       ┆ 172319.27    │
│ госслужащий     ┆ 150447.94    │
│ студент         ┆ 98201.63     │
│ в декрете       ┆ 53829.13     │
│ сотрудник       ┆ 142594.4     │
│ предприниматель ┆ 499163.14    │
└─────────────────┴──────────────┘
====================================================================================================

Видим, что единственный атрибут для значений которого медианное значение атрибута `total_income` значительно варьируется - это атрибут `income_type`. Сгруппируем данные по нему и заполним пропущенные значения. Так как мы группируем всего по одному атрибуту, то для заполнения пропущенных значений воспользуемся функцией по аналогии с программой курса.

In [52]:
# Заполнение total_income по income_type медианами (реализовано в следующей ячейке)

In [53]:
df = df.with_columns(
    pl.when(pl.col('total_income').is_null())
    .then(
        pl.when(pl.col('income_type') == 'безработный').then(131339.75)
        .when(pl.col('income_type') == 'в декрете').then(53829.13)
        .when(pl.col('income_type') == 'госслужащий').then(150521.92)
        .when(pl.col('income_type') == 'компаньон').then(172268.93)
        .when(pl.col('income_type') == 'пенсионер').then(118557.18)
        .when(pl.col('income_type') == 'предприниматель').then(499163.14)
        .when(pl.col('income_type') == 'сотрудник').then(142594.40)
        .when(pl.col('income_type') == 'студент').then(98201.63)
        .otherwise(pl.col('total_income'))
    )
    .otherwise(pl.col('total_income'))
    .alias('total_income')
)

Проверим:

In [54]:
df['total_income']

shape: (21_519,)
Series: 'total_income' [f64]
[
	253875.639453
	112080.014102
	145885.952297
	267628.550329
	158616.07787
	255763.565419
	240525.97192
	135823.934197
	95856.832424
	144425.938277
	…
	109486.327999
	322807.776603
	178059.553491
	153864.650328
	115949.039788
	224791.862382
	155999.806512
	89672.561153
	244093.0505
	82047.418899
]

**Вывод**

При изучении данных помимо явных прропусков удалось найти атрибуты с неявными пропусками или не информативно заполенными значениями.

1. В атрибуте `children` присудствовало значени -1
2. В атрибуте `dob_years` - значение 0
3. В атрибуте `gender` - XNA
4. В атрибутах `days_employed` и `total_income` - явные пропуски в данных.

Путем статистических проверок было выявлено, что все вышеперечисленные пропуски относятся к классу "Полностью случайные". Они были с учетом группировок по другим атрибутам (признакам).

### Замена типа данных

В нашем датафрейме только у двух атрибутов тип данных вещественный - `days_employed` и `total_income`, их и переведем в целочисленный формат.

Воспользуемся методом `.astype()`, так второй метод из теории курса `to_numeric()` переводит данные в вещественный тип.

In [ ]:
df = df.with_columns([
    pl.col('days_employed').cast(pl.Int64),
    pl.col('total_income').cast(pl.Int64)
])

**Вывод**

Для замены вещественного типа данных на целочисленные, как описано в задании - воспользуемся методом `.astype()`, так второй метод из теории курса `to_numeric()` переводит данные в вещественный тип.

### Обработка дубликатов

Переведем значения во всех атрибутах с типом  `objects` в нижний регистр. Для того, чтобы избавиться от неявных дубликатов в атрибуте `education`. Остальные атрибуты обработаны для красоты =)

In [ ]:
df = df.with_columns([
    pl.col(c).str.to_lowercase().alias(c)
    for c in ['education', 'family_status', 'gender', 'income_type', 'purpose']
])

Теперь методом `duplicated()`посмотрим есть ли явные дубликаты в данных.

Перед тем как проверить данные на явные дубликаты было бы хорошо леммитизировать атрибут `purpose` и при помощи стемминга привести его значения к единому стилю, но по регламенту проекта данные действия идут позже.

In [ ]:
df.filter(pl.struct(pl.all()).is_duplicated())

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
2849,0,1772,41,среднее,1,женат / замужем,0,f,сотрудник,0,142594,покупка жилья для семьи
3290,0,15259,58,среднее,1,гражданский брак,1,f,пенсионер,0,118557,сыграть свадьбу
4181,1,1583,34,высшее,0,гражданский брак,1,f,сотрудник,0,142594,свадьба
4850,0,15200,60,среднее,1,гражданский брак,1,f,пенсионер,0,118557,свадьба
5556,0,15259,58,среднее,1,гражданский брак,1,f,пенсионер,0,118557,сыграть свадьбу
...,...,...,...,...,...,...,...,...,...,...,...,...
20696,0,15282,64,среднее,1,женат / замужем,0,f,пенсионер,0,118557,дополнительное образование
21026,0,15200,60,среднее,1,женат / замужем,0,f,пенсионер,0,118557,заняться образованием
21126,0,2155,47,среднее,1,женат / замужем,0,f,сотрудник,0,142594,ремонт жилью
21275,1,1308,30,высшее,0,женат / замужем,0,f,сотрудник,0,142594,покупка коммерческой недвижимости
21409,0,15279,54,среднее,1,женат / замужем,0,f,пенсионер,0,118557,операции с жильем

Для того, чтобы понять причины наличия дубликатов в данных, давайте возьмем значения о клиенте находящемся под индексом 2835 и выведем все строки в датафрейме относящиеся к нему.

Судя по тому, что один и тот же клиент фигурирует в данных как с одинаковыми значениями атрибута `purpose`, так и с разными, то можно сделать вывод, что он мог более чем один раз обратиться в банк, за получением кредита либо на один и те же нужды либо же на разные.

Подобного рода вопрос можно решить путем добавления версионности в данные.

In [ ]:
df.filter(
    (pl.col('children') == 0) & (pl.col('days_employed') == 1772)
    & (pl.col('dob_years') == 41) & (pl.col('education_id') == 1)
    & (pl.col('family_status_id') == 0) & (pl.col('gender') == 'f')
    & (pl.col('income_type') == 'сотрудник')
)

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
1431,0,1772,41,среднее,1,женат / замужем,0,f,сотрудник,0,142594,покупка жилья для семьи
2849,0,1772,41,среднее,1,женат / замужем,0,f,сотрудник,0,142594,покупка жилья для семьи
3395,0,1772,41,среднее,1,женат / замужем,0,f,сотрудник,0,142594,свой автомобиль
4552,0,1772,41,среднее,1,женат / замужем,0,f,сотрудник,0,142594,операции со своей недвижимостью
5985,0,1772,41,среднее,1,женат / замужем,0,f,сотрудник,0,142594,покупка недвижимости
6253,0,1772,41,среднее,1,женат / замужем,0,f,сотрудник,0,142594,строительство недвижимости
13115,0,1772,41,среднее,1,женат / замужем,0,f,сотрудник,1,142594,строительство собственной недвижимости
19284,0,1772,41,среднее,1,женат / замужем,0,f,сотрудник,0,142594,профильное образование
19553,0,1772,41,среднее,1,женат / замужем,0,f,сотрудник,0,142594,свой автомобиль

Явные дубликаты в данных присудствуют - избавимся от них методом `drop_duplicates()`

In [ ]:
df = df.unique()

**Вывод**

В атрибуте `education` значения приведены в разном регистре, перед тем как проверить данные на явные дубликаты необходимо было привести их в единый регистр.

<div class="alert alert-success">
<b>✔️ Комментарий ревьюера:</b> Удалять дубли можно только после полной обработки данных. Верно! </div>

### Лемматизация

Леммитизируем значения в атрибуте `purpose`.
Одна из библиотек с функцией лемматизации на русском языке — pymystem3, разработана сотрудниками Яндекса.

In [ ]:
from pymystem3 import Mystem
m = Mystem()

In [ ]:
# Лемматизация purpose: join(lemmatize(x)) без последнего символа (перенос строки)
df = df.with_columns(
    pl.col('purpose').map_elements(lambda x: "".join(m.lemmatize(x))[:-1], return_dtype=pl.Utf8).alias('purpose')
)
df['purpose']

0                     покупка жилье
1           приобретение автомобиль
2                     покупка жилье
3        дополнительный образование
4                   сыграть свадьба
                    ...
21443              операция с жилье
21444           сделка с автомобиль
21445                  недвижимость
21446    на покупка свой автомобиль
21447         на покупка автомобиль
Name: purpose, Length: 21448, dtype: object

**Вывод**

В атрибуте `purpose` занчения записываются в произвольном формате, для его необходимо лиммитизировать слова в значении атрибута. Далее на основе лемм слов можно произвести категоризацию данного атрибута.

### Категоризация данных

#### Атрибут `dob_years`

Первый атриубут по которому можно провести категоризацию данных - это атрибут `dob_years`. Для этого воспользуемся функцие из теоретической части тернажера.

In [ ]:
def age_group(age):
    """
    Возвращает возрастную группу по значению возраста age, используя правила:
    - 'дети', если age <= 18 лет;
    - 'взрослые', если age от 19 до 64;
    - 'пенсионеры' — от 65 и старше.
    """
    
    if age <= 18:
        return 'дети'
    if age <= 64:
        return 'взрослые'
    return 'пенсионеры'

In [ ]:
df = df.with_columns(
    pl.col('dob_years').map_elements(age_group, return_dtype=pl.Utf8).alias('dob_years_group')
)
df.head(10)

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose,dob_years_group
0,1,8438,42,высшее,0,женат / замужем,0,f,сотрудник,0,253875,покупка жилье,взрослые
1,1,4025,36,среднее,1,женат / замужем,0,f,сотрудник,0,112080,приобретение автомобиль,взрослые
2,0,5623,33,среднее,1,женат / замужем,0,m,сотрудник,0,145885,покупка жилье,взрослые
3,3,4125,32,среднее,1,женат / замужем,0,m,сотрудник,0,267628,дополнительный образование,взрослые
4,0,14178,53,среднее,1,гражданский брак,1,f,пенсионер,0,158616,сыграть свадьба,взрослые
5,0,926,27,высшее,0,гражданский брак,1,m,компаньон,0,255763,покупка жилье,взрослые
6,0,2879,43,высшее,0,женат / замужем,0,f,компаньон,0,240525,операция с жилье,взрослые
7,0,153,50,среднее,1,женат / замужем,0,m,сотрудник,0,135823,образование,взрослые
8,2,6930,35,высшее,0,гражданский брак,1,f,сотрудник,0,95856,на проведение свадьба,взрослые
9,0,2189,41,среднее,1,женат / замужем,0,m,сотрудник,0,144425,покупка жилье для семья,взрослые

#### Атрибут `purpose`

Аналогичным образом можем поступить и с атрибутом `purpose`.

Для разнообразия проделаем действия аналогичные функции `age_group`, только при помощи `lambda`-функции

In [ ]:
def purpose_to_group(x):
    if x is None:
        return None
    if 'коммерческая недвижимость' in x:
        return 'коммерческая недвижимость'
    if 'недвижимость' in x or 'жилье' in x:
        return 'недвижимость'
    if 'автомобиль' in x:
        return 'автомобиль'
    if 'образование' in x:
        return 'образование'
    if 'свадьба' in x:
        return 'свадьба'
    return None

df = df.with_columns(
    pl.col('purpose').map_elements(purpose_to_group, return_dtype=pl.Utf8).alias('purpose_group')
)
df.head(10)

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose,dob_years_group,purpose_group
0,1,8438,42,высшее,0,женат / замужем,0,f,сотрудник,0,253875,покупка жилье,взрослые,недвижимость
1,1,4025,36,среднее,1,женат / замужем,0,f,сотрудник,0,112080,приобретение автомобиль,взрослые,автомобиль
2,0,5623,33,среднее,1,женат / замужем,0,m,сотрудник,0,145885,покупка жилье,взрослые,недвижимость
3,3,4125,32,среднее,1,женат / замужем,0,m,сотрудник,0,267628,дополнительный образование,взрослые,образование
4,0,14178,53,среднее,1,гражданский брак,1,f,пенсионер,0,158616,сыграть свадьба,взрослые,свадьба
5,0,926,27,высшее,0,гражданский брак,1,m,компаньон,0,255763,покупка жилье,взрослые,недвижимость
6,0,2879,43,высшее,0,женат / замужем,0,f,компаньон,0,240525,операция с жилье,взрослые,недвижимость
7,0,153,50,среднее,1,женат / замужем,0,m,сотрудник,0,135823,образование,взрослые,образование
8,2,6930,35,высшее,0,гражданский брак,1,f,сотрудник,0,95856,на проведение свадьба,взрослые,свадьба
9,0,2189,41,среднее,1,женат / замужем,0,m,сотрудник,0,144425,покупка жилье для семья,взрослые,недвижимость

#### Атрибут `total_income`

Категоризируем клиентов банка по уровню дохода.

Пороги выбраны субъективно, так как в зависимости от информации в интернете данные пороги разные.

При реальном случае решения подобной задачи необходимо узнать, есть ли у банка аналитика по данному вопросу и брать именно те пороги, которые определил сам банк в ходе анализа.

In [ ]:
# Категории по доходу: до 13890 (МРОТ), до 60000, до 150000, выше
df = df.with_columns(
    pl.when(pl.col('total_income') <= 13890).then(pl.lit('ниже прожиточного минимуму'))
    .when(pl.col('total_income') <= 60000).then(pl.lit('низкий уровень дохода'))
    .when(pl.col('total_income') <= 150000).then(pl.lit('средний уровень дохода'))
    .otherwise(pl.lit('высокий уровень дохода'))
    .alias('total_income_group')
)
df.head(10)

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose,dob_years_group,purpose_group,total_income_group
0,1,8438,42,высшее,0,женат / замужем,0,f,сотрудник,0,253875,покупка жилье,взрослые,недвижимость,высокий уровень дохода
1,1,4025,36,среднее,1,женат / замужем,0,f,сотрудник,0,112080,приобретение автомобиль,взрослые,автомобиль,средний уровень дохода
2,0,5623,33,среднее,1,женат / замужем,0,m,сотрудник,0,145885,покупка жилье,взрослые,недвижимость,средний уровень дохода
3,3,4125,32,среднее,1,женат / замужем,0,m,сотрудник,0,267628,дополнительный образование,взрослые,образование,высокий уровень дохода
4,0,14178,53,среднее,1,гражданский брак,1,f,пенсионер,0,158616,сыграть свадьба,взрослые,свадьба,высокий уровень дохода
5,0,926,27,высшее,0,гражданский брак,1,m,компаньон,0,255763,покупка жилье,взрослые,недвижимость,высокий уровень дохода
6,0,2879,43,высшее,0,женат / замужем,0,f,компаньон,0,240525,операция с жилье,взрослые,недвижимость,высокий уровень дохода
7,0,153,50,среднее,1,женат / замужем,0,m,сотрудник,0,135823,образование,взрослые,образование,средний уровень дохода
8,2,6930,35,высшее,0,гражданский брак,1,f,сотрудник,0,95856,на проведение свадьба,взрослые,свадьба,средний уровень дохода
9,0,2189,41,среднее,1,женат / замужем,0,m,сотрудник,0,144425,покупка жилье для семья,взрослые,недвижимость,средний уровень дохода

**Вывод**

Категоризация клиентов проделана по атрибутам `dob_years`, `purpose`, `total_income`. Остальные атрибуты и так являются категориальными за исключением атрибута `days_employed`. Пороги выбраны субъективно. По атрибуту `days_employed` категоризацию не проводил, так как данный параметр не очень объективный и не может говорить об уровне специалиста.

## Шаг 3. Ответьте на вопросы

- Есть ли зависимость между наличием детей и возвратом кредита в срок?

In [ ]:
print(f"Доля клиентов с детьми, вернушие кредит: \
{(df.filter(pl.col('children') == 0).select(pl.col('debt').mean()).item() * 100):0.2f}%")
print(f"Доля клиентов без детей, вернушие кредит: \
{(df.filter(pl.col('children') != 0).select(pl.col('debt').mean()).item() * 100):0.2f}%")

Доля клиентов с детьми, вернушие кредит: 7.53%
Доля клиентов без детей, вернушие кредит: 9.25%

**Вывод**

Зависимость между возвратом кредита и наличием детей есть. Среди клиентов без детей примерно на 2.22% больше случаев возврата кредита. Вероятно, что это связано с тем, что у таких клиентов меньше потенциальных расходов.

<div class="alert alert-success">
<b>✔️ Комментарий ревьюера:</b> Верно </div>

- Есть ли зависимость между семейным положением и возвратом кредита в срок?

In [ ]:
print("Доля клиентов вернуших кредит. Разбивка по семейному положению:")
df.group_by('family_status').agg(pl.col('debt').mean() * 100)

Доля клиентов вернуших кредит. Разбивка по семейному положению:

family_status
в разводе                7.112971
вдовец / вдова           6.569343
гражданский брак         9.353905
женат / замужем          7.546405
не женат / не замужем    9.754361
Name: debt, dtype: float64

**Вывод**

Клиенты находящиеся в гражданоском браке либо не имеющие формальных отношений чаще возвращают кредит чем те, кто имеет или имел супруга. Видимо вывод можно сделать такое же, как и в предыдушем пункте - меньше расходов. А также возможно менее крупные суммы для кредитов.

- Есть ли зависимость между уровнем дохода и возвратом кредита в срок?


Воспользуемся атрибутом `total_income_group` для ответа на вопрос.

In [ ]:
print("Доля клиентов вернуших кредит. Разбивка по уровню дохода:")
df.group_by('total_income_group').agg(pl.col('debt').mean() * 100)

Доля клиентов вернуших кредит. Разбивка по целям кредита:

total_income_group
высокий уровень дохода    7.763533
низкий уровень дохода     6.079404
средний уровень дохода    8.590716
Name: debt, dtype: float64

**Вывод**

Разница невелика, но чаще всего кредит возвращают люди со средним доходом. Реже всего люди с низким доходом.

- Как разные цели кредита влияют на его возврат в срок?

Воспользуемся атрибутом `purpose_group` для ответа на вопрос.

In [ ]:
print("Доля клиентов вернуших кредит. Разбивка по целям кредита:")
df.group_by('purpose_group').agg(pl.col('debt').mean() * 100)

Доля клиентов вернуших кредит. Разбивка по целям кредита:

purpose_group
автомобиль      9.361208
недвижимость    7.235381
образование     9.222333
свадьба         8.006888
Name: debt, dtype: float64

**Вывод**

Хуже всего возвращают кредит те клиенты, которые взяли деньги на недвижимость, а лучше всего клиенты, взявшие кредит на авто или образование. Видимо это связано с величиной сумм. Проще закрыть кредит за авто или за образование в сравнении с кредитом на недвижимость.

<div class="alert alert-success">
<b>✔️ Комментарий ревьюера:</b> Все так </div>

## Шаг 4. Общий вывод

1. Название колонок определены без стилистических нарушений
2. Данные довольно сырые, помимо явных пропусков в атрибутах присутствуют некорректно заполненные значения.
    - в атрибуте `children` присутствуют значения -1
    - `dob_year` - присутствуют значения 0
    - `total_income` - пропущенные значения 
    Все эти атрибуты были заполнены медианными значениями категорий, на которые поделили строки датафрейма.
    
3. В атрибуте `gender` - присутствуют значение 'XNA' в силу небольшого объема таких значений от общего данные строки были просто удалены

4. `days_employed` - пропуски в данном атрибуте также были заполнены медианными значениями, но предварительно его заполнения были приведены в единый формат:
    - отрицательные значения атрибута приведены в днях
    - положительные в часах
    
5. При обработке пропусков потребовалось привести значения в атрибуте `education` в нижний регистр.
6. В атрибуте `purpose` значения записываются в произвольном формате, для чего необходимо лиммитизировать слова в значении атрибута. Далее на основе лемм слов можно произвести категоризацию данного атрибута

7. Категоризация клиентов проделана по атрибутам `dob_years`, `purpose`, `total_income`. Остальные атрибуты и так являются категориальными за исключением атрибута `days_employed`. Пороги выбраны субъективно. По атрибуту `days_employed` категоризацию не проводил, так как данный параметр не очень объективный и не может говорить об уровне специалиста

8. Среди клиентов без детей примерно на 2.22% больше случаев возврата кредита. Вероятно, что это связано с тем, что у таких клиентов меньше потенциальных расходов

9. Клиенты, находящиеся в гражданском браке либо не имеющие формальных отношений чаще возвращают кредит чем те, кто имеет или имел супруга. Видимо вывод можно сделать такое же, как и в предыдущем пункте - меньше расходов. А также возможно менее крупные суммы для кредитов

10. Разница невелика, но чаще всего кредит возвращают люди со средним доходом. Реже всего люди с низким доходом

11. Хуже всего возвращают кредит те клиенты, которые взяли деньги на недвижимость, а лучше всего клиенты, взявшие кредит на авто или образование. Видимо это связано с величиной сумм. Проще закрыть кредит за авто или за образование в сравнении с кредитом на недвижимость.

12. На мой субъективный взгляд стат. характеристики у разных группу клиентов примерно одинаковое - выборка хорошо сбалансирована

13. В данных преимущественно категориальные переменные - это стоит учесть при выборе модели